---
prompt_file: prompts/eli5_default_llama2_selfcitation.json
eval_file: data/eli5_eval_bm25_top100.json
shot: 0
ndoc: 5
dataset_name: eli5
tag: bm25
model: meta-llama/Llama-2-7b-chat-hf
temperature: 1.0
top_p: 0.95
