---
prompt_file: prompts/eli5_default_zephyr_selfcitation.json
eval_file: data/eli5_eval_bm25_top100.json
shot: 0
ndoc: 5
dataset_name: eli5
tag: bm25
model: HuggingFaceH4/zephyr-7b-beta
temperature: 0.7
top_p: 0.95
